### PR TITLE
Release 4.0.0

### PR DESCRIPTION
**Pull request by Nyholm**
Are we ready for 4.0.0 or should we do something else before the release?

### CODE REVIEW

**Comment by sstok** [comment]
Maybe drop support for Symfony 2.7 as well?

**Comment by Nyholm** [comment]
Sure. Let’s only support 3,4 and 4.x. 

Can you make a PR?

//Tobias Nyholm

**Comment by greg0ire** [comment]
I think there are some type hints that can be added too

**Comment by greg0ire** [comment]
Something else to consider: adding `final` keywords here or there.

**Comment by Nyholm** [comment]
Excellent idea. Could you open a new PR with the `final` keyword added?

**Comment by greg0ire** [comment]
I'm on it. How about moving the code into `src`?

**Comment by Nyholm** [comment]
That is a BC break indeed. But do we need it? Should we “risk” making the upgrade path harder just for “esthetic” changes?

**Comment by greg0ire** [comment]
You mean for `src`? I'm not even sure this is a BC-break at all… the class names will be the same. IIRC in Sonata, we did it in a pedantic patch (lower than patch, no changelog needed).

**Comment by garak** [comment]
+1 for moving source code under `src`

**Comment by greg0ire** [comment]
@Nyholm FYI for me it's not esthetic as much as practical: I had series of commands like grep or php-cs-fixer I wanted to do on the source code only.

**Comment by sstok** [comment]
PSR-4 allows to do this without affecting the namespace in anyway (I actually did it multiple times), only if someone didn't use Composer they might experience a BC, but this feels like a massive edge-case 😄

**Comment by emodric** [comment]
Hi. Any news on release (and #115)?

**Comment by enumag** [comment]
What is left to be done before 4.0 can be released? Can we help with a PR?

**Comment by Nyholm** [comment]
Thank you for all the reviews and for the PRs.

**Comment by Nyholm** [comment]
(Just waiting for Travis)

**Pull request merged**
