### PR TITLE
Final keywords

### PR DESCRIPTION
**Pull request by greg0ire**
To be rebased on master once #114 is merged

### CODE REVIEW

**Comment by greg0ire** [comment]
Hah it's funny, there is the same method twice in a child and parent class:

https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/blob/969080c0607ebe18f8e230a605609d0d51b33e33/PhpUnit/AbstractContainerBuilderTestCase.php#L69-L75

https://github.com/SymfonyTest/SymfonyDependencyInjectionTest/blob/969080c0607ebe18f8e230a605609d0d51b33e33/PhpUnit/AbstractExtensionTestCase.php#L63-L69

I think this must be a mistake

**Comment by Nyholm** [comment]
I’ve merged #114

**Comment by sstok** [comment]
The (new) method signature style seems inconsistent with others, should these be on a single line or chopped-down? 

Personally I favor the single-line as these lines are not to long and it's consistent with the Symfony coding standard 👍

**Comment by greg0ire** [comment]
> The (new) method signature style seems inconsistent with others, should these be on a single line or chopped-down?

Depends on the length of the line.

> Personally I favor the single-line as these lines are not to long 

They are over 120 chars though, so I'd ask you to define "too long"? I think there should ideally be no need for horizontal scrolling when reviewing code…

**Comment by sstok** [comment]
142 characters, hmm :) I guess this is due the long method names 😄 no strong feelings, I only noticed the method signatures where different. Personally I keep them on a single line, independent of the number of arguments.

**Comment by Nyholm** [comment]
Great work. @greg0ire 

Im fine with the single line

**Pull request merged**
