### PR TITLE
Service/alias names might be fqcns

### PR DESCRIPTION
**Pull request by vudaltsov**
removed strtolower

### CODE REVIEW

**Comment by stloyd** [comment]
Can you add test for this change?

**Comment by vudaltsov** [comment]
@stloyd , done

**Comment by matthiasnoback** [comment]
Hmm, I wonder why I've actually added `strtolower()` in the first place. Did the DI component to do this at some point too? @xabbuh, do you by any chance know this? Do you think this is a safe change?

**Comment by sstok** [comment]
Symfony in the past lowercased service ids, but this is deprecated in Symfony 3.3 and removed in Symfony 4. Service ids are then used as-is.

**Comment by xabbuh** [comment]
@sstok is right here. So technically this change may lead to new reports in existing applications that used to work. However, I think that's okay as it will make them aware that they have to make changes to be able to update to Symfony 4.

**Comment by stloyd** [comment]
@vudaltsov Merged, thanks!

**Comment by Nyholm** [comment]
Merging this broke master. 
Could you create a new PR that fixes the issues introduced?

**Pull request merged**
